### ISSUE TITLE
dev HEAD fails to compile on macOS

### ISSUE THREAD

**Issue by rex4539** [gandrewstone/bitcoin#1206]
```
Making all in src
  OBJCXX   qt/bitcoin_qt-macdockiconhandler.o
  CXX      qt/libbitcoinqt_a-peertablemodel.o
  CXX      qt/libbitcoinqt_a-platformstyle.o
  CXX      qt/libbitcoinqt_a-qvalidatedlineedit.o
  CXX      qt/libbitcoinqt_a-qvaluecombobox.o
  CXX      qt/libbitcoinqt_a-rpcconsole.o
  CXX      qt/libbitcoinqt_a-splashscreen.o
  CXX      qt/libbitcoinqt_a-trafficgraphwidget.o
  CXX      qt/libbitcoinqt_a-utilitydialog.o
  CXX      qt/libbitcoinqt_a-addressbookpage.o
  CXX      qt/libbitcoinqt_a-addresstablemodel.o
  CXX      qt/libbitcoinqt_a-askpassphrasedialog.o
qt/macdockiconhandler.mm:54:2: error: #elif without #if
#elif QT_VERSION >= 0x050200
 ^
qt/macdockiconhandler.mm:56:2: error: #endif without #if
#endif
 ^
2 errors generated.
make[2]: *** [qt/bitcoin_qt-macdockiconhandler.o] Error 1

**Comment by ptschip** [comment]
did you rerun ./autogen.sh and ./configure?

can you try to compile again and also do a make clean as well...

**Comment by rex4539** [comment]
```
qt/macdockiconhandler.mm:54:2: error: #elif without #if
#elif QT_VERSION >= 0x050200
 ^
qt/macdockiconhandler.mm:56:2: error: #endif without #if
#endif
 ^
In file included from qt/optionsmodel.cpp:19:
In file included from ./main.h:16:
In file included from ./chain.h:12:
In file included from ./primitives/block.h:12:
./sync.h:163:5: warning: mutex 'scs' is not held on every path through here [-Wthread-safety-analysis]
    }
    ^
./sync.h:160:17: note: mutex acquired here
            scs.lock();
                ^
./sync.h:170:17: warning: releasing mutex 'scs' that was not held [-Wthread-safety-analysis]
            scs.unlock();
                ^
2 warnings generated.
  CXX      qt/libbitcoinqt_a-utilitydialog.o
In file included from qt/peertablemodel.cpp:6:
In file included from ./qt/peertablemodel.h:9:
In file included from ./main.h:16:
In file included from ./chain.h:12:
In file included from ./primitives/block.h:12:
./sync.h:163:5: warning: mutex 'scs' is not held on every path through here [-Wthread-safety-analysis]
    }
    ^
./sync.h:160:17: note: mutex acquired here
            scs.lock();
                ^
./sync.h:170:17: warning: releasing mutex 'scs' that was not held [-Wthread-safety-analysis]
            scs.unlock();
                ^
2 warnings generated.
  CXX      qt/libbitcoinqt_a-addressbookpage.o
  CXX      qt/libbitcoinqt_a-addresstablemodel.o
2 errors generated.
make[2]: *** [qt/bitcoin_qt-macdockiconhandler.o] Error 1

```

**Comment by ptschip** [comment]
@sickpig can you look into this one, I seem to remember some changes a
while back about fixing the QT version, looks like something went
missing here...

**Comment by sickpig** [comment]
Will have a look.

**Comment by sickpig** [comment]
@rex4539 should be fixed by https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/1207

**Comment by rex4539** [comment]
I pulled #1207, ran make clean, autogen and configure again but the build still fails (different error).

```
Making all in src
  CXX      libbitcoin_server_a-graphene.o
  CXX      libbitcoin_server_a-rest.o
  CXX      rpc/libbitcoin_server_a-blockchain.o
  CXX      rpc/libbitcoin_server_a-mining.o
  CXX      rpc/libbitcoin_server_a-misc.o
  CXX      rpc/libbitcoin_server_a-net.o
  CXX      rpc/libbitcoin_server_a-rawtransaction.o
  CXX      rpc/libbitcoin_server_a-server.o
In file included from graphene.cpp:5:
In file included from ./graphene.h:11:
./graphene_set.h:273:18: warning: variable length array used [-Wvla]
        bool bits[nEncodedWords * WORD_BITS];
                 ^
./graphene_set.h:300:18: warning: variable length array used [-Wvla]
        bool bits[nEncodedWords * WORD_BITS];
                 ^
In file included from graphene.cpp:5:
In file included from ./graphene.h:13:
In file included from ./primitives/block.h:12:
./sync.h:163:5: warning: mutex 'scs' is not held on every path through here [-Wthread-safety-analysis]
    }
    ^
./sync.h:160:17: note: mutex acquired here
            scs.lock();
                ^
./sync.h:170:17: warning: releasing mutex 'scs' that was not held [-Wthread-safety-analysis]
            scs.unlock();
                ^
graphene.cpp:182:14: warning: declaration shadows a local variable [-Wshadow]
        CInv inv(CInv(MSG_BLOCK, grapheneBlockTx.blockhash));
             ^
graphene.cpp:73:10: note: previous declaration is here
    CInv inv(MSG_GRAPHENEBLOCK, grapheneBlockTx.blockhash);
         ^
graphene.cpp:116:43: warning: comparison of integers of different signs: 'std::__1::vector<CTransaction, std::__1::allocator<CTransaction> >::size_type' (aka 'unsigned long') and 'int' [-Wsign-compare]
    if (grapheneBlockTx.vMissingTx.size() < pfrom->grapheneBlockWaitingForTxns)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
graphene.cpp:722:13: warning: releasing mutex 'cs_xval' that was not held [-Wthread-safety-analysis]
            LEAVE_CRITICAL_SECTION(cs_xval); // maintain locking order with vNodes
            ^
./sync.h:461:14: note: expanded from macro 'LEAVE_CRITICAL_SECTION'
        (cs).unlock();             \
             ^
graphene.cpp:733:13: warning: mutex 'cs_xval' is not held on every path through here [-Wthread-safety-analysis]
        if (pfrom->nLocalGrapheneBlockBytes > maxAllowedSize)
            ^
graphene.cpp:731:13: note: mutex acquired here
            ENTER_CRITICAL_SECTION(cs_xval);
            ^
./sync.h:456:14: note: expanded from macro 'ENTER_CRITICAL_SECTION'
        (cs).lock();                                           \
             ^
graphene.cpp:748:1: warning: mutex 'cs_xval' is not held on every path through here [-Wthread-safety-analysis]
}
^
graphene.cpp:725:17: note: mutex acquired here
                ENTER_CRITICAL_SECTION(cs_xval);
                ^
./sync.h:456:14: note: expanded from macro 'ENTER_CRITICAL_SECTION'
        (cs).lock();                                           \
             ^
In file included from graphene.cpp:5:
In file included from ./graphene.h:8:
In file included from ./bloom.h:10:
./serialize.h:771:6: error: member reference base type 'unsigned long' is not a structure or union
    a.Unserialize(is);
    ~^~~~~~~~~~~~
./serialize.h:1107:7: note: in instantiation of function template specialization 'Unserialize<CDataStream, unsigned long>' requested here
    ::Unserialize(s, arg);
      ^
./serialize.h:1126:7: note: in instantiation of function template specialization 'UnserializeMany<CDataStream, unsigned long>' requested here
    ::UnserializeMany(s, args...);
      ^
./graphene_set.h:344:9: note: in instantiation of function template specialization 'SerReadWriteMany<CDataStream, unsigned long>' requested here
        READWRITE(nReceiverUniverseItems);
        ^
./serialize.h:203:27: note: expanded from macro 'READWRITE'
#define READWRITE(...) (::SerReadWriteMany(s, ser_action, __VA_ARGS__))
                          ^
./graphene_set.h:338:5: note: in instantiation of function template specialization 'CGrapheneSet::SerializationOp<CDataStream, CSerActionUnserialize>' requested here
    ADD_SERIALIZE_METHODS;
    ^
./serialize.h:220:9: note: expanded from macro 'ADD_SERIALIZE_METHODS'
        SerializationOp(s, CSerActionUnserialize());                 \
        ^
./serialize.h:771:7: note: in instantiation of function template specialization 'CGrapheneSet::Unserialize<CDataStream>' requested here
    a.Unserialize(is);
      ^
./serialize.h:1107:7: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    ::Unserialize(s, arg);
      ^
./graphene.h:85:9: note: in instantiation of function template specialization 'SerReadWriteMany<CDataStream, CGrapheneSet>' requested here
        READWRITE(*pGrapheneSet);
        ^
./serialize.h:203:27: note: expanded from macro 'READWRITE'
#define READWRITE(...) (::SerReadWriteMany(s, ser_action, __VA_ARGS__))
                          ^
./graphene.h:71:5: note: in instantiation of function template specialization 'CGrapheneBlock::SerializationOp<CDataStream, CSerActionUnserialize>' requested here
    ADD_SERIALIZE_METHODS;
    ^
./serialize.h:220:9: note: expanded from macro 'ADD_SERIALIZE_METHODS'
        SerializationOp(s, CSerActionUnserialize());                 \
        ^
./serialize.h:771:7: note: in instantiation of function template specialization 'CGrapheneBlock::Unserialize<CDataStream>' requested here
    a.Unserialize(is);
      ^
./streams.h:290:11: note: in instantiation of function template specialization 'Unserialize<CDataStream, CGrapheneBlock>' requested here
        ::Unserialize(*this, obj);
          ^
graphene.cpp:321:11: note: in instantiation of function template specialization 'CDataStream::operator>><CGrapheneBlock>' requested here
    vRecv >> grapheneBlock;
          ^
In file included from graphene.cpp:5:
In file included from ./graphene.h:8:
In file included from ./bloom.h:10:
./serialize.h:765:6: error: member reference base type 'const unsigned long' is not a structure or union
    a.Serialize(os);
    ~^~~~~~~~~~
./serialize.h:1089:7: note: in instantiation of function template specialization 'Serialize<CSizeComputer, unsigned long>' requested here
    ::Serialize(s, std::forward<Arg>(arg));
      ^
./serialize.h:1120:7: note: in instantiation of function template specialization 'SerializeMany<CSizeComputer, unsigned long &>' requested here
    ::SerializeMany(s, std::forward<Args>(args)...);
      ^
./graphene_set.h:344:9: note: in instantiation of function template specialization 'SerReadWriteMany<CSizeComputer, unsigned long &>' requested here
        READWRITE(nReceiverUniverseItems);
        ^
./serialize.h:203:27: note: expanded from macro 'READWRITE'
#define READWRITE(...) (::SerReadWriteMany(s, ser_action, __VA_ARGS__))
                          ^
./graphene_set.h:338:5: note: in instantiation of function template specialization 'CGrapheneSet::SerializationOp<CSizeComputer, CSerActionSerialize>' requested here
    ADD_SERIALIZE_METHODS;
    ^
./serialize.h:215:27: note: expanded from macro 'ADD_SERIALIZE_METHODS'
        NCONST_PTR(this)->SerializationOp(s, CSerActionSerialize()); \
                          ^
./serialize.h:765:7: note: in instantiation of function template specialization 'CGrapheneSet::Serialize<CSizeComputer>' requested here
    a.Serialize(os);
      ^
./serialize.h:1089:7: note: (skipping 3 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    ::Serialize(s, std::forward<Arg>(arg));
      ^
./graphene.h:71:5: note: in instantiation of function template specialization 'CGrapheneBlock::SerializationOp<CSizeComputer, CSerActionSerialize>' requested here
    ADD_SERIALIZE_METHODS;
    ^
./serialize.h:215:27: note: expanded from macro 'ADD_SERIALIZE_METHODS'
        NCONST_PTR(this)->SerializationOp(s, CSerActionSerialize()); \
                          ^
./serialize.h:765:7: note: in instantiation of function template specialization 'CGrapheneBlock::Serialize<CSizeComputer>' requested here
    a.Serialize(os);
      ^
./serialize.h:1072:11: note: in instantiation of function template specialization 'Serialize<CSizeComputer, CGrapheneBlock>' requested here
        ::Serialize(*this, obj);
          ^
./serialize.h:1139:44: note: in instantiation of function template specialization 'CSizeComputer::operator<<<CGrapheneBlock>' requested here
    return (CSizeComputer(nType, nVersion) << t).size();
                                           ^
graphene.cpp:1326:40: note: in instantiation of function template specialization 'GetSerializeSize<CGrapheneBlock>' requested here
            int nSizeGrapheneBlock = ::GetSerializeSize(grapheneBlock, SER_NETWORK, PROTOCOL_VERSION);
                                       ^
In file included from graphene.cpp:5:
In file included from ./graphene.h:8:
In file included from ./bloom.h:10:
./serialize.h:765:6: error: member reference base type 'const unsigned long' is not a structure or union
    a.Serialize(os);
    ~^~~~~~~~~~
./serialize.h:1089:7: note: in instantiation of function template specialization 'Serialize<CDataStream, unsigned long>' requested here
    ::Serialize(s, std::forward<Arg>(arg));
      ^
./serialize.h:1120:7: note: in instantiation of function template specialization 'SerializeMany<CDataStream, unsigned long &>' requested here
    ::SerializeMany(s, std::forward<Args>(args)...);
      ^
./graphene_set.h:344:9: note: in instantiation of function template specialization 'SerReadWriteMany<CDataStream, unsigned long &>' requested here
        READWRITE(nReceiverUniverseItems);
        ^
./serialize.h:203:27: note: expanded from macro 'READWRITE'
#define READWRITE(...) (::SerReadWriteMany(s, ser_action, __VA_ARGS__))
                          ^
./graphene_set.h:338:5: note: in instantiation of function template specialization 'CGrapheneSet::SerializationOp<CDataStream, CSerActionSerialize>' requested here
    ADD_SERIALIZE_METHODS;
    ^
./serialize.h:215:27: note: expanded from macro 'ADD_SERIALIZE_METHODS'
        NCONST_PTR(this)->SerializationOp(s, CSerActionSerialize()); \
                          ^
./serialize.h:765:7: note: in instantiation of function template specialization 'CGrapheneSet::Serialize<CDataStream>' requested here
    a.Serialize(os);
      ^
./serialize.h:1089:7: note: (skipping 3 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    ::Serialize(s, std::forward<Arg>(arg));
      ^
./graphene.h:71:5: note: in instantiation of function template specialization 'CGrapheneBlock::SerializationOp<CDataStream, CSerActionSerialize>' requested here
    ADD_SERIALIZE_METHODS;
    ^
./serialize.h:215:27: note: expanded from macro 'ADD_SERIALIZE_METHODS'
        NCONST_PTR(this)->SerializationOp(s, CSerActionSerialize()); \
                          ^
./serialize.h:765:7: note: in instantiation of function template specialization 'CGrapheneBlock::Serialize<CDataStream>' requested here
    a.Serialize(os);
      ^
./streams.h:282:11: note: in instantiation of function template specialization 'Serialize<CDataStream, CGrapheneBlock>' requested here
        ::Serialize(*this, obj);
          ^
./net.h:656:20: note: in instantiation of function template specialization 'CDataStream::operator<<<CGrapheneBlock>' requested here
            ssSend << a1;
                   ^
graphene.cpp:1338:24: note: in instantiation of function template specialization 'CNode::PushMessage<CGrapheneBlock>' requested here
                pfrom->PushMessage(NetMsgType::GRAPHENEBLOCK, grapheneBlock);
                       ^
9 warnings and 3 errors generated.
make[2]: *** [libbitcoin_server_a-graphene.o] Error 1
```

**Comment by ptschip** [comment]
PR 1212 should contain the additional fixe needed...can you try to
compile that one?  thx

**Comment by rex4539** [comment]
Now it fails with

```
In file included from test/test_bitcoin_fuzzy.cpp:9:
In file included from ./addrman.h:8:
In file included from ./netaddress.h:18:
./serialize.h:765:6: error: member reference base type 'const unsigned long' is not a structure or union
    a.Serialize(os);
    ~^~~~~~~~~~
./streams.h:282:11: note: in instantiation of function template specialization 'Serialize<CDataStream, unsigned long>' requested here
        ::Serialize(*this, obj);
          ^
test/test_bitcoin_fuzzy.cpp:444:21: note: in instantiation of function template specialization 'CDataStream::operator<<<unsigned long>' requested here
                out << iblt->size();
                    ^
4 warnings and 1 error generated.
make[2]: *** [test/test_bitcoin_fuzzy-test_bitcoin_fuzzy.o] Error 1
```

**Comment by ptschip** [comment]
@awemany this looks like you're code..bitcoin fuzzy?

**Comment by ptschip** [comment]
can you try to compile without tests for now,

 do a ./configure --disable-tests and then compile

**Comment by rex4539** [comment]
After pulling #1222, it fails with:

```
In file included from test/graphene_tests.cpp:1:
In file included from ./bloom.h:10:
./serialize.h:765:6: error: member reference base type 'const unsigned long' is not a structure or union
    a.Serialize(os);
    ~^~~~~~~~~~
./hash.h:175:11: note: in instantiation of function template specialization 'Serialize<CHashWriter, unsigned long>' requested here
        ::Serialize(*this, obj);
          ^
./hash.h:220:8: note: in instantiation of function template specialization 'CHashWriter::operator<<<unsigned long>' requested here
    ss << obj;
       ^
test/graphene_tests.cpp:66:25: note: in instantiation of function template specialization 'SerializeHash<unsigned long>' requested here
            auto hash = SerializeHash(i-SEED);
                        ^
4 warnings and 1 error generated.
make[2]: *** [test/test_bitcoin-graphene_tests.o] Error 1
```

**Comment by ptschip** [comment]
ok we'll try this again.... can you try to compile #1228 ?  thx.

**Comment by awemany** [comment]
@ptschip: I see your change b106c1de. I agree that this should do it regarding serialization of `CIBlt::size()`. Thank you. Or is there any other issue regarding the fuzzer code?

**Comment by rex4539** [comment]
#1228 fixed the final issue.

It now compiles without errors.

Thanks to all who contributed :)

**Comment by ptschip** [comment]
thanks for your patience :)
