### ISSUE TITLE
Bitcoin Unlimited Cash Edition.app 1.6.0.0 for Mac hangs on quitting application.

### ISSUE THREAD

**Issue by Afron-Lysias** [gandrewstone/bitcoin#1718]
Bitcoin Unlimited Cash Edition.app 1.6.0.0 for Mac hangs on quitting application.

System Version: OS X 10.11.6 (15G22010)

**Comment by sickpig** [comment]
Thanks for opening the issue. Will look into it

**Comment by jcramer** [comment]
I also am having this problem on both mainnet and testnet.

**Comment by greatwolf** [comment]
I'm getting the same issue on Win7 64-bit. It's hanging on the dialog indefinitely: "Bitcoin Unlimited Cash Edition is shutting down... Do not shut down the computer until this window disappears."

**Comment by ptschip** [comment]
thx for the report... we are aware of it and will hopefully have a fix
soon...

**Comment by greatwolf** [comment]
Just wanted to add, another symptom I'm seeing is that activating the best chain takes a long while during startup. My guess is this is probably due to me having to forcibly kill the client through task manager.

From googling around, activating best chain seems to indicate that it's processing blocks it already downloaded but has not yet committed to disk from last run. Of course in this case it probably couldn't commit the processed blocks because it's just hanging at the shut down dialog.

**Comment by ptschip** [comment]
yes, that behavior is expected....

**Comment by ptschip** [comment]
are you able to build your own bitcoind?  if so there is a PR open which
may fix this issue, if you want to give it a test... It's PR 1753 on the
BU gihub.

**Comment by ptschip** [comment]
are you able to build your own bitcoind?  if so there is a PR open which
may fix this issue, if you want to give it a test... It's PR 1753
"cleanup finalize node" on the BU github.

**Comment by sickpig** [comment]
@Afron-Lysias @greatwolf @jcramer #1775 should fix this issue. Will be included in the next release if merged. If you are willing to compile from source you could give it a try.

**Comment by sickpig** [comment]
#1775 should fix this. closing. 

@Afron-Lysias @greatwolf @jcramer feel free to reopen in case current `dev` is not working for you.

**Comment by Afron-Lysias** [comment]
Bitcoin Unlimited Cash Edition.app 1.6.0.1 for Mac **still** hangs on quitting application.

**Comment by greatwolf** [comment]
I just had a chance to try 1.6.0.1, like @Afron-Lysias I'm also still hanging upon shutting down. Please reopen this issue as it appears to still be a problem.

**Comment by ptschip** [comment]
Hi thanks for the report.  I talked with Andrew about it but it's not a
high priority for us right now.

Question:  are you just shutting down and having a fully synced chain, 
or are you shutting down while you're still doing initial sync?

**Comment by greatwolf** [comment]
This is with the client sync'ed to the latest block, (the lower right icon shows the checkmark). I am running my client in prune node however.

**Comment by ptschip** [comment]
is there any message with the crash?  anything in the log file?

**Comment by greatwolf** [comment]
As far as I can tell there isn't any crash, the client is just waiting at the small shutdown dialog indefinitely. The client itself is still able to respond to events, eg. it can still be maximized and minimized but the background cleanup on exit just never finishes.

The last couple of lines debug.log:

    2019-07-26 20:45:03 tor: Thread interrupt
    2019-07-26 20:45:03 torcontrol thread exit
    2019-07-26 20:45:13 Shutdown: In progress...
    2019-07-26 20:45:13 StopNode()

**Comment by Afron-Lysias** [comment]
Same issue on Ubuntu 18.04.2 LTS. 
Chains fully synced on both macOS and Ubuntu desktops.
Same debug.log output:
`2019-07-28 11:07:10 Shutdown: In progress...`
`2019-07-28 11:07:10 StopNode()`

**Comment by ptschip** [comment]
are you using the versions that were downloaded from our website or did
you compile them yourself locally?

are you running the UI with the wallet enabled?

I have an 18.04.2 vm , i'll try a sync on there with pruning enabled and
see if it happens for me.

**Comment by Afron-Lysias** [comment]
Binaries downloaded from BU’s site. 
Wallet enabled.  
conf:
listen=1
upnp=1
maxmempool=600

**Comment by Afron-Lysias** [comment]
After a number of tests, I think I found something:
Having set `upnp=0` in bitcoin.conf, the problem goes away. BU app quits as expected.

**Comment by ptschip** [comment]
confirmed, happens for me on windows too...great sleuthing :)

will have to take a look next week and come up with a fix.

thanks!

**Comment by ptschip** [comment]
thanks, found the problem and fixed...will be in the next release.  The
upnp thread wasn't exiting properly when it got a shutdown request.

aOn 28/07/2019 7:36 a.m., Afron-Lysias wrote:
