### ISSUE TITLE
Improperly explained reduction of max connections

### ISSUE THREAD

**Issue by monsterbitar** [gandrewstone/bitcoin#2179]
I configured my BU node with an excessively large max connections and the log output resulted in:

```
Warning: Reducing -maxconnections from 1024 to 873, because of system limitations.
```

Some digging later and it seems that this "system limitation"  seems to have been a matter of available file descriptors (as talked about here, for example https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/1587). Raising the soft and hard user limit for open files with ulimit to 4096 and I can now see this in my debug log:

```
Using at most 873 connections (4096 file descriptors available)
```

The log message indicates that it should have 4096 file descriptors available, but that it's using at most 873 connections. The relation is difficult to grasp.

Could this be documented better? (instead of generic "system limitation", name the actual limitation at play here?)

**Comment by Greg-Griffith** [comment]
a file descriptor is itself an abstract handler for some system resource to do OS stuff. Im not sure how else you would describe the limitation other than saying its a file descriptor limit. 

that being said, it looks like this issue and #2177 are both occurring due to a logic flow issue where we are doing some things out of order. i should have a PR with a fix for this momentarily.

**Comment by monsterbitar** [comment]
I'd be happy if this is only a matter of one resource (FDs), then updating the initial message to state the actual limitation should be relatively straightforward.

I'll be happy to recompile and test the PR once it's ready.

**Comment by Greg-Griffith** [comment]
#2180 should fix this issue

**Comment by monsterbitar** [comment]
recompiling to test now.

**Comment by monsterbitar** [comment]
NOTE: while this might fix the reduction, it doesn't fix this issue. This issue is about the log message being unclear in it's explanation of the issue by calling it a "system limitation" when first presented to the user which can very easily lead the user to go down a wide range of rabbitholes trying to figure out **what** limitation is encountered.

If said user weren't an impatient millenial, he might've read a few more lines of the debug log and found the 2nd message which is much more clear.

My suggestion is to update the first message to reference the file descriptor count just like the 2nd message does, as that is very useful.

**Comment by Greg-Griffith** [comment]
I will change the errors once i determine if the only limitation this is affected by is file descriptors. I am still looking into windows. AFAICT they use a different system.

**Comment by monsterbitar** [comment]
Recompilation done and I've experimented with larger numbers to see if I could cause anything to break horrible. So far, I haven't been able to see anything breaking.

These three messages might be worth looking at when you're ready to update to more clear text:

```
2020-04-19 09:52:04 Warning: Reducing -maxconnections from 9999 to 8041, because of system limitations.
2020-04-19 09:52:04 Reducing -maxoutconnections from 9999 to 8041, because this value is higher than max available connections.
2020-04-19 09:52:04 Using at most 8041 connections (8192 file descriptors available)
```

first one says `system limitation`, second one says `max available connections` and third one says `file descriptors`.

I understand there's some math going on to reserve a minimum number of descriptors for other purposes which determines the max available connections, but that all three of these seems to be bound by file descriptors and it would be helpful to point users in that direction.

**Comment by Greg-Griffith** [comment]
windows does not have file descriptors, they use a few different things because windows, unlike unitx, does not consider everything a file. 

I have adjusted the messages to be more descriptive.

using your example above, the new output would be 
```
2020-04-19 09:52:04 Warning: Reducing -maxconnections from %d to %d because of file descriptor limitations (unix) or winsocket fd_set limitations (windows). If you are a windows user there is a hard upper limit of 1024 which cannot be changed by adjusting the node's configuration.
2020-04-19 09:52:04 Reducing -maxoutconnections from 9999 to 8041, because this value is higher than max available connections.
2020-04-19 09:52:04 Using at most 8041 connections
```

**Comment by monsterbitar** [comment]
thank you, having the most relevant information be seen first is a good change.
