### ISSUE TITLE
Debug Window - Peers Tab doesn't always reflect changes related to banned nodes.

### ISSUE THREAD

**Issue by Justaphf** [gandrewstone/bitcoin#89]
Environment: Windows 10
Client: v0.12.1c - built from source (32-bit)

On the "Debug window" dialog, the banned nodes table, which appears below the currently connected nodes list when banned nodes are present, does not update when nodes have been banned/unbanned by any means other than direct user action, specifically related to banning/unbanning nodes, either through the UI or RPC calls.  Upon direct user interaction through the UI/RPC to ban/unban a node, the UI then updates to correctly display the state of all banned nodes, regardless if it was the specific node the user interacted with.

Symptoms:
1. When the ban time expires and a node is no longer banned, the banned peer table doesn't refresh to remove it.  This can cause the node to show up both in the banned peer table AND as a connected node if it successfully reconnects.
2. I also detected a secondary issue, that when a ban expires, the RPC call `listbanned` still contains the node, even though the ban has expired AND the node has successfully reconnected.
3. When a node gets banned due to some internally detected reason (misbehaving), the banned peer table does not refresh to add it.

The only way I've gotten the UI to update is by manually setting the ban state of a node through UI or RPC, or by restarting bitcoin-qt.exe.  Closing and reopening the dialog does not seem to cause a refresh.

**Comment by ptschip** [comment]
not that it shouldn't get fixed but i believe that's something i've seen for a long time... the list is not
getting refreshed when a node gets banned unless it's by the user himself.

**Comment by sickpig** [comment]
@ptschip @Justaphf sorry for the late reply. Has this issue been solved in the mean time? 

If this is not the case I wonder if this commit by Cory Fields could fix the problem at hand 
```
commit 8b8f87714df8c1e0868e6411c8f09c838ea736ab
Author: Cory Fields <cory-nospam-@coryfields.com>
Date:   Mon Apr 18 17:02:43 2016 -0400

    net: make Ban/Unban/ClearBan functionality consistent
    
    - Ban/Unban/ClearBan call uiInterface.BannedListChanged() as necessary
    - Ban/Unban/ClearBan sync to disk if the operation is user-invoked
    - Mark node for disconnection automatically when banning
    - Lock cs_vNodes while setting disconnected
    - Don't spin in a tight loop while setting disconnected
```

On a s side note I wonder if this one is worth porting 
```
commit f4ac02ee7c6530c273503d8575a492e9b2ac1f13
Author: Kaz Wesley <keziahw@gmail.com>
Date:   Wed Apr 27 09:26:33 2016 -0700

    fix race that could fail to persist a ban
    
    DumpBanList currently does this:
      - with lock: take a copy of the banmap
      - perform I/O (write out the banmap)
      - with lock: mark the banmap non-dirty
    If a new ban is added during the I/O operation, it may never be persisted to
    disk.
    
    Reorder operations so that the data to be persisted cannot be older than the
    time at which the banmap was marked non-dirty.
```

**Comment by ptschip** [comment]
it's a good thing to fix but nothing urgent...it's really just a
nuisance bug.  I'll put it on my list for the next release unless
someone else wants to go ahead and fix it first.

**Comment by Justaphf** [comment]
The issue still exists.  As ptschip said it has existed for a long time.  I haven't looked at the commit, but based on the description of 8b8f877 above it sounds like the first point fixes this issue, plus several other items, so it may be worth cherry picking.  I'm trying to finish off my automated scripts for setting up the dev environment in Windows in my spare time, but if no one picks this up I can probably look at it in a couple of weeks.

**Comment by Justaphf** [comment]
Fixed by #262
